site_name: Myo Htet
nav:
  - Home: home.md
  - Contact: contact.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
